DOMAIN = "systemnexa2"

CONF_HOST = "host"
CONF_PORT = "port"
CONF_TOKEN = "token"
CONF_NAME = "name"
CONF_POLL_INTERVAL = "poll_interval"

DEFAULT_NAME = "WPD-01"
DEFAULT_PORT = 3000
DEFAULT_POLL_INTERVAL = 10

PLATFORMS = ["light"]